### ISSUE TITLE
the file X_train_256_v2.npy can't be build?

### ISSUE THREAD

**Issue by YUN-XIAO-MO** [Tirth27/Detecting-diabetic-retinopathy#5]
respected sir，I come from gregwchase/eyenet ---2018, I saw your message in the issue.May I ask how you solve the question that the file X_train_256_v2.npy can't be build?

**Comment by Tirth27** [comment]
Hi @YUN-XIAO-MO , the file `X_train_256_v2.npy` that you want to create is just the numpy array (i.e. `.npy` or `.npz`).

It is nothing but a numpy array of training images (X_train) off resolution 256x256.

When I initially worked on the project, I tried to build the numpy array based on the [this](https://github.com/Tirth27/Detecting-diabetic-retinopathy/blob/master/src/Preprocessing%20Scripts/Train/5_image_to_array.py) and [this](https://github.com/gregwchase/eyenet/blob/master/src/image_to_array.py), but found that it is not the ideal way to do it. Because if you create a numpy array on training images(X_train) then I will be of size ~14GiB. And when training a model you have to load that ~14GiB of numpy array in the RAM. Which requires more RAM and computation. 

So, I suggest if you can use the [flow_from_directory](https://github.com/Tirth27/Detecting-diabetic-retinopathy/blob/86ba4fe616e15f72f509f1ed17a5b2dae8c84b88/src/Model/model.py#L206) then you can augment the images on fly, during model training. You can find more resources on [Keras Website](https://keras.io/api/preprocessing/image/) and its [explanation of Medium](https://vijayabhaskar96.medium.com/tutorial-image-classification-with-keras-flow-from-directory-and-generators-95f75ebe5720)

**Comment by YUN-XIAO-MO** [comment]
I'am glad that you responsed quickly.

I did get the warn that the RAM of the GPU is not enough.

So,I decrease the training set,I picked a little piece from the whole training set to try the model.

But my computer only have one GPU, I changed the code from [gregwchase](https://github.com/gregwchase/eyenet/blob/master/src/cnn.py) to fit my computer.

here is [my code](https://github.com/YUN-XIAO-MO/learning/blob/main/cnn_me).

I use X_train to try the model, but i got a bug,I show you the traceback:
`Splitting data into test/ train datasets
Reshaping Data
X_train Shape:  (2462, 256, 256, 3)
X_test Shape:  (616, 256, 256, 3)
Normalizing Data
y_train Shape:  (2462, 2)
y_test Shape:  (616, 2)
Training Model
2022-01-25 14:05:22.483986: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-25 14:05:24.082647: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 0
2022-01-25 14:05:24.085044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1669 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Model flattened out to:  (None, 438048)
2022-01-25 14:05:24.516928: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1548484608 exceeds 10% of free system memory.
Traceback (most recent call last):
  File "D:\Desktop\Python_WorkSpace\workspace\EYE\src\cnn_test.py", line 154, in <module>
    model = cnn_model(X_train=X_train,
  File "D:\Desktop\Python_WorkSpace\workspace\EYE\src\cnn_test.py", line 83, in cnn_model
    model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch,
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\data_adapter.py", line 1420, in _make_class_weight_map_fn
    class_ids = list(sorted(class_weight.keys()))
AttributeError: 'str' object has no attribute 'keys'`

Would you mind helping me with this problem.

**Comment by Tirth27** [comment]
Hi @YUN-XIAO-MO , I was not able to properly debug the code, would be mind providing detail about what changes you made in your script from the originals. Plus, what you wanted to achieve. 

And if you can provide the full error logs to better understand the issue.

**Comment by YUN-XIAO-MO** [comment]
Thank you, honourable  sir. @Tirth27 

I uploaded my [details](https://github.com/YUN-XIAO-MO/learning/blob/main/changes_details.txt)。

I just want to make the model work。

**Comment by Tirth27** [comment]
If you look at [Keras Model APIs](https://keras.io/api/models/model_training_apis/) `class_weight` in the `model.fit()` takes dictionary, but you passed the string. 

Direct quote from the website:
> class_weight: Optional dictionary mapping class indices (integers) to a weight (float) value, used for weighting the loss function (during training only). This can be useful to tell the model to "pay more attention" to samples from an under-represented class.

Also, you might be interested in [this](https://stackoverflow.com/questions/64123445/python-attributeerror-str-object-has-no-attribute-keys) discussion on StackOverflow
